# Generated by Django 5.0.2 on 2024-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=4)),
                ('album', models.CharField(max_length=50)),
            ],
        ),
    ]
