# Generated by Django 5.0.3 on 2024-03-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artista', models.CharField(max_length=30)),
                ('icone_artista', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
                ('banner_artista', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
                ('background_gradient', models.CharField(blank=True, max_length=200)),
                ('vizualizacoes_mensais', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_album', models.CharField(max_length=30)),
                ('foto_album', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
                ('ano_lancamento', models.IntegerField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_musica', models.CharField(max_length=30)),
                ('vizualizacoes_musica', models.IntegerField()),
                ('duracao', models.DurationField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.album')),
            ],
        ),
    ]
