# Generated by Django 5.0.3 on 2024-03-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='icone_artista',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d'),
        ),
    ]
