# Generated by Django 5.0.1 on 2024-03-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_artista_icone_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='vizualizacoes_mensais',
            new_name='visualizacoes_mensais',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='vizualizacoes_musica',
            new_name='visualizacoes_musica',
        ),
    ]
