# Generated by Django 5.0.1 on 2024-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_vizualizacoes_mensais_artista_visualizacoes_mensais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='background_gradient',
        ),
        migrations.AlterField(
            model_name='artista',
            name='icone_artista',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
