# Generated by Django 5.0.1 on 2024-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_artista_background_gradient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='audio_mp3',
            field=models.FileField(blank=True, upload_to='musicas/%Y/%m/%d'),
        ),
    ]
